version: '3.8'

services:
  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shree-samagri-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - shree-samagri-network
    depends_on:
      - db
      - redis

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: shree-samagri-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shree-samagri-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: shree-samagri-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shree_samagri
      MYSQL_ROOT_PASSWORD: Sagar@$26
      MYSQL_USER: shree_user
      MYSQL_PASSWORD: shree$@2025
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - shree-samagri-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: shree-samagri-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - shree-samagri-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shree-samagri-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Sagar@$26
    ports:
      - "8080:80"
    networks:
      - shree-samagri-network
    depends_on:
      - db

networks:
  shree-samagri-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
